Use RDS Aurora for the next stack
ministryofjustice/bichard7-next-infrastructure pull request #54
Opened 2021-01-22 15:30 UTC by bjpirt

2021-01-22 17:09 UTC, brettminnie requested changes

2021-01-22 17:09 UTC, brettminnie commented on shared_terraform/stack_infra_baseline/main.tf
> +  db_endpoint          = [module.db2.internal_ip]
You renamed the module to db, so db2 won't work here

2021-01-22 17:09 UTC, brettminnie commented on shared_terraform/stack_infra_next/main.tf
> +  rds_database_name             = "bichard"
Do we not want to set these as vars if we're feeding them into the module

2021-01-22 17:09 UTC, brettminnie commented on terraform/stack_infra_next/main.tf
> +  rds_master_username           = "bichard"
Same as above regarding vars

2021-01-22 17:09 UTC, brettminnie commented on terraform_modules/aurora/main.tf
> +  special = true
Watch this. Postgres can complain with special chars in the connection string 

See https://jasonaowen.net/blog/2017/Feb/09/aws-postgresql-rds-passwords/

2021-01-22 17:09 UTC, brettminnie commented on terraform_modules/aurora/main.tf
> +  name_prefix = var.environment_name
Please add a description to the SG

2021-01-22 17:09 UTC, brettminnie commented on terraform_modules/aurora/variables.tf
> +  description = "The name of the environment"
Add a type

2021-01-22 17:09 UTC, brettminnie commented on terraform_modules/aurora/variables.tf
> +variable "vpc_id" {
Add a type and with the vars below

2021-01-25 08:46 UTC, bjpirt commented on shared_terraform/stack_infra_baseline/main.tf
> +  db_endpoint          = [module.db2.internal_ip]
This one still has db2 as the module

2021-01-25 08:47 UTC, bjpirt commented on shared_terraform/stack_infra_next/main.tf
> +  rds_database_name             = "bichard"
They are set as vars in the Aurora module, do they need setting elsewhere?

2021-01-25 08:47 UTC, bjpirt commented on terraform/stack_infra_next/main.tf
> +  rds_master_username           = "bichard"
likewise

2021-01-25 08:48 UTC, bjpirt commented on terraform_modules/aurora/main.tf
> +  special = true
We're not using a connection string, this gets configured as an env var on the WAS container and then configured into WAS at startup.

2021-01-25 08:50 UTC, bjpirt commented on terraform_modules/aurora/main.tf
> +  name_prefix = var.environment_name
Have added types and descriptions for all vars now

2021-01-25 08:54 UTC, brettminnie commented on shared_terraform/stack_infra_next/main.tf
> +  rds_database_name             = "bichard"
I was referring to having the option of passing them into this terraform from the outside world with these values as defaults

2021-01-25 08:55 UTC, brettminnie approved these changes

2021-01-25 08:55 UTC, merged