Integrate the SQS -> MQ lambda into the deployment pipeline
ministryofjustice/bichard7-next-infrastructure pull request #61
Opened 2021-01-26 17:27 UTC by TheGrantsta

Amends the SQS queue policy to allow lambda

Creates SQS trigger to lambda

Create lambda function that decrypts message and sends the body to HEARING_OUTCOME_INPUT_QUEUE

Logs result to CloudWatch

2021-01-26 18:10 UTC, brettminnie requested changes

2021-01-26 18:10 UTC, brettminnie commented on terraform/stack_infra_next/main.tf
>    tags                = module.label.tags
For future reference as a convention, tags should be at the bottom of a resource block on their own line

2021-01-26 18:10 UTC, brettminnie commented on terraform_modules/sqs-ingress/main.tf
> +  assume_role_policy = <<EOF
If you write this as <<-EOF you can indent like a real person ;)

2021-01-26 18:10 UTC, brettminnie commented on terraform_modules/sqs-ingress/main.tf
>  data "aws_iam_policy_document" "sendMessage" {
please change this to send_message to match convention

2021-01-26 18:18 UTC, TheGrantsta commented
Changes implemented

2021-01-26 19:07 UTC, brettminnie commented on terraform_modules/sqs-ingress/main.tf
>    policy    = data.aws_iam_policy_document.sendMessage.json
this needs to be changed to the new name too

2021-01-27 08:54 UTC, TheGrantsta commented on terraform_modules/sqs-ingress/main.tf
>    policy    = data.aws_iam_policy_document.sendMessage.json
Whoops! Fixed

2021-01-27 09:01 UTC, brettminnie approved these changes

2021-01-27 09:01 UTC, merged